import Link from "next/link";
import { Ban, Flag, ShieldCheck } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { requireViewer } from "@/lib/auth";
import { unreadNotificationCount } from "@/lib/data";
import { titleCase } from "@/lib/format";
import { unblockProfileAction } from "@/lib/social-actions";

export default async function SafetyPage(){
 const {supabase,user}=await requireViewer(); const [unread,{data:reports},{data:blocks}]=await Promise.all([unreadNotificationCount(supabase,user.id),supabase.from("oj_reports").select("id,entity_kind,entity_id,reason,status,created_at").eq("reporter_id",user.id).order("created_at",{ascending:false}).limit(50),supabase.from("oj_blocks").select("blocked_id,created_at").eq("blocker_id",user.id).order("created_at",{ascending:false})]); const ids=(blocks??[]).map(b=>b.blocked_id); let profiles:any[]=[]; if(ids.length){const {data}=await supabase.from("oj_profiles").select("id,username,full_name").in("id",ids); profiles=data??[];} const map=new Map(profiles.map(p=>[p.id,p]));
 return <div className="page-wrap"><AppHeader title="Safety" eyebrow="Move with confidence" unread={unread}/><section className="safety-principles"><article><ShieldCheck/><h3>Behaviour over vibes</h3><p>Reliability and verified organizer signals come from actual Ojoro behaviour. We avoid turning people into five-star products.</p></article><article><Flag/><h3>Report anything unsafe</h3><p>Activities, clans, people, posts and messages can be reported from the surface where they happen.</p></article><article><Ban/><h3>Blocking is immediate</h3><p>Blocking removes social discovery and follow relationships. You stay in control of who can interact with you.</p></article></section>
 <section className="content-section"><div className="section-heading"><div><span className="section-kicker">Blocked</span><h3>People you’ve blocked</h3></div><span>{blocks?.length??0}</span></div>{blocks?.length?<div className="member-list">{blocks.map(b=>{const p=map.get(b.blocked_id);return <div className="member-row" key={b.blocked_id}><strong>{p?.full_name||p?.username||"Blocked member"}</strong><form action={unblockProfileAction}><input type="hidden" name="profile_id" value={b.blocked_id}/><input type="hidden" name="back" value="/safety"/><button className="button button-small button-ghost">Unblock</button></form></div>})}</div>:<p className="muted">No blocked people.</p>}</section>
 <section className="content-section"><div className="section-heading"><div><span className="section-kicker">Reports</span><h3>Your submitted reports</h3></div><span>{reports?.length??0}</span></div>{reports?.length?<div className="notification-list">{reports.map(r=><article className="notification-item" key={r.id}><Flag/><div><span className="section-kicker">{titleCase(r.entity_kind)}</span><h3>{r.reason}</h3><p>Status: {titleCase(r.status)}</p><small>{new Date(r.created_at).toLocaleString("en-CA")}</small></div></article>)}</div>:<p className="muted">You haven’t submitted any reports.</p>}</section><section className="quiet-note"><strong>Emergency situations</strong><p>Ojoro reporting is not an emergency service. If someone is in immediate danger, contact local emergency services and leave the situation when safe.</p><Link href="/people">Back to people</Link></section></div>;
}
