import Link from "next/link";
import { CalendarDays, Clock3, Download, MapPin } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { EmptyState } from "@/components/empty-state";
import { requireViewer } from "@/lib/auth";
import { unreadNotificationCount } from "@/lib/data";
import { formatActivityTime, sportEmoji, titleCase } from "@/lib/format";

export default async function CalendarPage(){
 const {supabase,user}=await requireViewer(); const [unread,{data:parts}]=await Promise.all([unreadNotificationCount(supabase,user.id),supabase.from("oj_activity_participants").select("activity_id,rsvp_status").eq("profile_id",user.id).in("rsvp_status",["going","maybe","waitlist"])]); const ids=(parts??[]).map(p=>p.activity_id); let rows:any[]=[]; if(ids.length){const {data}=await supabase.from("oj_activities").select("id,title,sport_slug,mode,city,location_name,starts_at,ends_at").in("id",ids).gte("starts_at",new Date().toISOString()).order("starts_at").limit(100); rows=data??[];} const rsvp=new Map((parts??[]).map(p=>[p.activity_id,p.rsvp_status]));
 const groups=new Map<string,any[]>(); for(const a of rows){const key=new Date(a.starts_at).toISOString().slice(0,10);groups.set(key,[...(groups.get(key)??[]),a]);}
 return <div className="page-wrap"><AppHeader title="Calendar" eyebrow="Your movement schedule" unread={unread} actions={<div className="button-row"><Link href="/api/calendar.ics" className="button button-ghost desktop-action"><Download size={16}/> Export .ics</Link><Link href="/create?type=activity" className="button button-dark desktop-action">Create activity</Link></div>}/>{rows.length?<div className="calendar-list">{[...groups.entries()].map(([date,items])=><section className="calendar-day" key={date}><div className="calendar-date"><CalendarDays/><div><strong>{new Intl.DateTimeFormat("en-CA",{weekday:"long"}).format(new Date(`${date}T12:00:00`))}</strong><span>{new Intl.DateTimeFormat("en-CA",{month:"long",day:"numeric"}).format(new Date(`${date}T12:00:00`))}</span></div></div><div>{items.map(a=><Link href={`/activities/${a.id}`} className="calendar-event" key={a.id}><span className="calendar-emoji">{sportEmoji(a.sport_slug)}</span><div><strong>{a.title}</strong><small><Clock3 size={14}/>{formatActivityTime(a.starts_at)} · {titleCase(String(rsvp.get(a.id)||"going"))}</small><small><MapPin size={14}/>{a.location_name}, {a.city}</small></div></Link>)}</div></section>)}</div>:<EmptyState title="Your calendar is wide open" body="Join an activity and it will appear here automatically." href="/discover" action="Find something to do"/>}<section className="quiet-note"><strong>Works with Apple, Google and Outlook</strong><p>Use the .ics export to add your current Ojoro plans to any standard calendar. Ojoro stays the source of truth for RSVP and waitlist state.</p><Link href="/api/calendar.ics"><Download size={14}/> Export Ojoro calendar</Link></section></div>;
}
