"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireViewer } from "@/lib/auth";
function back(id:string,key:string,message:string):never{redirect(`/tournaments/${id}?${key}=${encodeURIComponent(message.slice(0,180))}`);}
function message(error:{message?:string}|null,fallback:string){const raw=error?.message??"";if(raw.includes("REGISTRATION_CLOSED"))return"Registration is closed.";if(raw.includes("TOURNAMENT_FULL"))return"The tournament is full.";if(raw.includes("FORBIDDEN"))return"You do not have permission for that tournament action.";if(raw.includes("NOT_ENOUGH_ENTRIES"))return"At least two entries are required.";if(raw.includes("ROUND_INCOMPLETE"))return"Finish the current round before advancing.";return fallback;}
export async function registerTournamentTeamAction(formData:FormData){const {supabase}=await requireViewer();const id=String(formData.get("tournament_id")??"");const team=String(formData.get("team_id")??"");const {error}=await supabase.rpc("oj_register_tournament_entry",{target_tournament:id,target_team:team});if(error)back(id,"error",message(error,"Could not register that team."));revalidatePath(`/tournaments/${id}`);back(id,"notice","Team registered.");}
export async function updateTournamentStatusAction(formData:FormData){const {supabase}=await requireViewer();const id=String(formData.get("tournament_id")??"");const status=String(formData.get("status")??"");if(!["draft","registration","active","completed","cancelled"].includes(status))back(id,"error","Invalid tournament state.");const {error}=await supabase.from("oj_tournaments").update({status}).eq("id",id);if(error)back(id,"error","Could not update tournament status.");revalidatePath(`/tournaments/${id}`);back(id,"notice","Tournament status updated.");}
export async function generateTournamentFixturesAction(formData:FormData){const {supabase}=await requireViewer();const id=String(formData.get("tournament_id")??"");const {data,error}=await supabase.rpc("oj_generate_tournament_fixtures",{target_tournament:id});if(error)back(id,"error",message(error,"Could not generate fixtures."));revalidatePath(`/tournaments/${id}`);back(id,"notice",`${data??0} fixtures generated.`);}
export async function recordFixtureResultAction(formData:FormData){const {supabase}=await requireViewer();const id=String(formData.get("tournament_id")??"");const fixture=String(formData.get("fixture_id")??"");const home=Number(formData.get("home_score"));const away=Number(formData.get("away_score"));if(!Number.isInteger(home)||home<0||!Number.isInteger(away)||away<0)back(id,"error","Enter valid scores.");const {error}=await supabase.rpc("oj_record_fixture_result",{target_fixture:fixture,home_points:home,away_points:away});if(error)back(id,"error",message(error,"Could not save the result."));revalidatePath(`/tournaments/${id}`);back(id,"notice","Fixture result saved.");}
export async function advanceTournamentRoundAction(formData:FormData){const {supabase}=await requireViewer();const id=String(formData.get("tournament_id")??"");const {data,error}=await supabase.rpc("oj_advance_knockout_round",{target_tournament:id});if(error)back(id,"error",message(error,"Could not advance the bracket."));revalidatePath(`/tournaments/${id}`);back(id,"notice",data===0?"Tournament completed.":`${data} next-round fixtures created.`);}
