import Link from "next/link";
import { CalendarPlus, Flag, Plus, ShieldPlus, Swords } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { LocalDateTimeInput } from "@/components/local-date-time-input";
import { QueryNotice } from "@/components/empty-state";
import { createActivityAction, createChallengeAction, createClanAction } from "@/lib/actions";
import { createTournamentAction } from "@/lib/tournament-actions";
import { requireViewer } from "@/lib/auth";
import { unreadNotificationCount } from "@/lib/data";

const types=[{id:"activity",label:"Activity",icon:Plus,copy:"Game, run, class, session"},{id:"match",label:"Match",icon:Swords,copy:"Competitive activity"},{id:"clan",label:"Clan",icon:ShieldPlus,copy:"Build a community"},{id:"challenge",label:"Challenge",icon:Flag,copy:"Give people a target"},{id:"tournament",label:"Tournament",icon:CalendarPlus,copy:"Run a competition"}];

export default async function CreatePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const {supabase,user,profile}=await requireViewer(); const q=await searchParams; const type=typeof q.type==="string"?q.type:"activity"; const error=typeof q.error==="string"?q.error:null;
  const [{data:sports},{data:memberships},unread]=await Promise.all([supabase.from("oj_sports").select("slug,name").eq("active",true).order("name"),supabase.from("oj_clan_members").select("clan_id,role").eq("profile_id",user.id).eq("status","active"),unreadNotificationCount(supabase,user.id)]);
  const clanIds=(memberships??[]).map(m=>m.clan_id); let clans:any[]=[]; if(clanIds.length){const {data}=await supabase.from("oj_clans").select("id,name").in("id",clanIds).order("name");clans=data??[];}
  return <div className="page-wrap"><AppHeader title="Create" eyebrow="Make something happen" unread={unread}/><QueryNotice error={error}/>
    <div className="create-type-grid">{types.map(({id,label,icon:Icon,copy})=><Link key={id} href={`/create?type=${id}`} className={`create-type-card ${type===id?"active":""}`}><Icon/><strong>{label}</strong><small>{copy}</small></Link>)}</div>
    <section className="create-panel">
      {(type==="activity"||type==="match")&&<form action={createActivityAction} className="form-stack wide-form"><div className="form-heading"><span>{type==="match"?"Competitive match":"New activity"}</span><h2>{type==="match"?"Set the game up.":"Give people a reason to show up."}</h2><p>Only the essentials are required. Advanced settings stay out of the way.</p></div>
        <div className="field"><label htmlFor="title">Title</label><input id="title" name="title" placeholder={type==="match"?"Saturday 5v5 showdown":"Friday night 7v7"} required maxLength={120}/></div>
        <div className="form-grid-3"><div className="field"><label htmlFor="sport">Activity</label><select id="sport" name="sport" required><option value="">Choose</option>{sports?.map(s=><option value={s.slug} key={s.slug}>{s.name}</option>)}</select></div><div className="field"><label htmlFor="mode">Mode</label>{type==="match"?<><input type="hidden" name="mode" value="competitive"/><input value="Competitive" disabled/></>:<select id="mode" name="mode" defaultValue="social"><option value="social">Social</option><option value="fitness">Fitness</option><option value="learning">Learning</option><option value="competitive">Competitive</option></select>}</div><div className="field"><label htmlFor="skill">Level</label><select id="skill" name="skill" defaultValue="recreational"><option value="beginner">Beginner</option><option value="recreational">Recreational</option><option value="intermediate">Intermediate</option><option value="competitive">Competitive</option><option value="elite">Elite</option></select></div></div>
        <div className="form-grid-2"><div className="field"><label htmlFor="starts_at">Starts</label><LocalDateTimeInput id="starts_at" name="starts_at_iso"/></div><div className="field"><label htmlFor="duration_minutes">Duration</label><select id="duration_minutes" name="duration_minutes" defaultValue="90"><option value="30">30 min</option><option value="45">45 min</option><option value="60">1 hour</option><option value="90">1.5 hours</option><option value="120">2 hours</option><option value="180">3 hours</option></select></div></div>
        <div className="form-grid-2"><div className="field"><label htmlFor="location">Location</label><input id="location" name="location" placeholder="Jeanne-Mance Park" required/></div><div className="field"><label htmlFor="city">City</label><input id="city" name="city" defaultValue={profile.city??""} required/></div></div>
        <div className="form-grid-3"><div className="field"><label htmlFor="capacity">Max people</label><input id="capacity" name="capacity" type="number" min="1" max="10000" defaultValue="14" required/></div><div className="field"><label htmlFor="cost">Cost per person</label><input id="cost" name="cost" type="number" min="0" step="0.01" defaultValue="0"/></div><div className="field"><label htmlFor="visibility">Who can join?</label><select id="visibility" name="visibility" defaultValue="public"><option value="public">Public</option><option value="members">Clan members</option><option value="private">Private / invite</option></select></div></div>
        {clans.length>0&&<div className="field"><label htmlFor="clan_id">Host under a clan (optional)</label><select id="clan_id" name="clan_id"><option value="">Personal activity</option>{clans.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div>}
        <div className="field"><label htmlFor="description">Details (optional)</label><textarea id="description" name="description" maxLength={2000} placeholder="What should people know?"/></div><div className="field"><label htmlFor="equipment">What to bring (optional)</label><input id="equipment" name="equipment" placeholder="Cleats, water, dark/light shirt" maxLength={600}/></div>
        <label className="check-row"><input type="checkbox" name="urgent"/><span><strong>Last Spot Rescue</strong><small>Highlight this when you urgently need people to fill the activity.</small></span></label>
        <button className="button button-brand button-lg" type="submit">Create {type==="match"?"match":"activity"}</button></form>}

      {type==="clan"&&<form action={createClanAction} className="form-stack wide-form"><div className="form-heading"><span>New clan</span><h2>Build the group people keep coming back to.</h2><p>Clans can be single-sport or completely multi-sport.</p></div><div className="field"><label htmlFor="name">Clan name</label><input id="name" name="name" required maxLength={80} placeholder="Ojoro McGill"/></div><div className="form-grid-2"><div className="field"><label htmlFor="clan_city">City</label><input id="clan_city" name="city" defaultValue={profile.city??""} required/></div><div className="field"><label htmlFor="clan_visibility">Visibility</label><select id="clan_visibility" name="visibility"><option value="public">Public — anyone can join</option><option value="private">Private — requests required</option></select></div></div><div className="field"><label htmlFor="bio">What is this clan about?</label><textarea id="bio" name="bio" maxLength={1000}/></div><fieldset className="choice-field"><legend>Sports & activities</legend><div className="compact-choice-grid">{sports?.map(s=><label key={s.slug}><input type="checkbox" name="sports" value={s.slug}/><span>{s.name}</span></label>)}</div></fieldset><button className="button button-brand button-lg" type="submit">Create clan</button></form>}

      {type==="challenge"&&<form action={createChallengeAction} className="form-stack wide-form"><div className="form-heading"><span>New challenge</span><h2>Turn a goal into something people want to finish.</h2></div><div className="field"><label htmlFor="challenge_title">Challenge</label><input id="challenge_title" name="title" required maxLength={120} placeholder="Run 20 km this week"/></div><div className="form-grid-3"><div className="field"><label htmlFor="metric">Metric</label><input id="metric" name="metric" required placeholder="kilometres"/></div><div className="field"><label htmlFor="target">Target</label><input id="target" name="target" type="number" min="1" step="0.1" defaultValue="20" required/></div><div className="field"><label htmlFor="days">Length</label><input id="days" name="days" type="number" min="1" max="365" defaultValue="7" required/></div></div><div className="form-grid-2"><div className="field"><label htmlFor="scope">Who is it for?</label><select id="scope" name="scope"><option value="personal">Personal</option><option value="friends">Friends</option><option value="city">City</option><option value="global">Global</option></select></div><div className="field"><label htmlFor="reward">XP reward</label><input id="reward" name="reward" type="number" min="0" max="5000" defaultValue="300"/></div></div><div className="field"><label htmlFor="challenge_description">Details</label><textarea id="challenge_description" name="description" maxLength={1200}/></div><button className="button button-brand button-lg" type="submit">Launch challenge</button></form>}

      {type==="tournament"&&<form action={createTournamentAction} className="form-stack wide-form"><div className="form-heading"><span>New tournament</span><h2>Run the competition without spreadsheet chaos.</h2></div><div className="field"><label htmlFor="t_name">Tournament name</label><input id="t_name" name="name" required maxLength={120} placeholder="Montreal Fall Cup"/></div><div className="form-grid-3"><div className="field"><label htmlFor="t_sport">Sport</label><select id="t_sport" name="sport" required><option value="">Choose</option>{sports?.map(s=><option value={s.slug} key={s.slug}>{s.name}</option>)}</select></div><div className="field"><label htmlFor="format">Format</label><select id="format" name="format" defaultValue="round_robin"><option value="knockout">Knockout</option><option value="round_robin">Round robin</option><option value="group_knockout">Groups + knockout</option><option value="league">League</option><option value="ladder">Ladder</option></select></div><div className="field"><label htmlFor="max_entries">Max entries</label><input id="max_entries" name="max_entries" type="number" min="2" max="256" defaultValue="8"/></div></div><div className="form-grid-3"><div className="field"><label htmlFor="t_city">City</label><input id="t_city" name="city" defaultValue={profile.city??""} required/></div><div className="field"><label htmlFor="t_starts">Starts</label><LocalDateTimeInput id="t_starts" name="starts_at_iso"/></div><div className="field"><label htmlFor="t_days">Days</label><input id="t_days" name="days" type="number" min="1" max="90" defaultValue="1"/></div></div><button className="button button-brand button-lg" type="submit">Open registration</button></form>}
    </section>
  </div>;
}
