import Link from "next/link";
import { ArrowUpRight, CalendarDays, Flame, Plus, Radar, Users } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { ActivityCard } from "@/components/activity-card";
import { ClanCard } from "@/components/clan-card";
import { EmptyState, QueryNotice } from "@/components/empty-state";
import { requireViewer } from "@/lib/auth";
import { homeSnapshot, unreadNotificationCount } from "@/lib/data";
import { createPostAction, setStatusAction } from "@/lib/actions";
import { percent, sportEmoji } from "@/lib/format";

export default async function HomePage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const { supabase, user, profile } = await requireViewer();
  const [snapshot, unread, query] = await Promise.all([homeSnapshot(supabase,user.id,profile.city),unreadNotificationCount(supabase,user.id),searchParams]);
  const error=typeof query.error==="string"?query.error:null; const success=query.status?"Your status is live for 12 hours.":query.post?"Posted.":null;
  const firstName=(profile.full_name??String(profile.username)).split(" ")[0];
  return <div className="page-wrap"><AppHeader title={`Hey, ${firstName}.`} eyebrow={profile.city ? `Today in ${profile.city}` : "Today on Ojoro"} unread={unread}/><QueryNotice error={error} success={success}/>
    <section className="daily-hero"><div><span className="daily-label"><Radar size={15}/> Ojoro Daily</span><h2>What are you doing <em>today?</em></h2><p>{snapshot.suggestions.length ? `${snapshot.suggestions.length} joinable activities are on your radar.` : "Your city gets better when somebody starts something."}</p></div><div className="daily-actions"><Link href="/discover?now=1" className="button button-dark button-lg">Find something now</Link><Link href="/create?type=activity" className="button button-light button-lg"><Plus size={18}/> Create activity</Link></div></section>

    <div className="quick-grid"><article className="quick-card"><Flame/><div><strong>Level {profile.level}</strong><small>{profile.lifetime_xp.toLocaleString()} lifetime XP</small></div></article><article className="quick-card"><CalendarDays/><div><strong>{snapshot.upcoming.length} upcoming</strong><small>Your confirmed and maybe plans</small></div></article><article className="quick-card"><Users/><div><strong>{snapshot.clans.length} clans</strong><small>Communities you show up with</small></div></article></div>

    <section className="content-section"><div className="section-title-row"><div><span className="section-kicker">Your calendar</span><h2>Coming up</h2></div><Link href="/discover">Find more <ArrowUpRight size={16}/></Link></div>{snapshot.upcoming.length ? <div className="horizontal-cards">{snapshot.upcoming.map(a=><ActivityCard key={a.id} activity={a}/>)}</div> : <EmptyState title="Nothing locked in yet" body="Find one thing worth showing up for. Ojoro will keep the rest organized." href="/discover" action="Explore activities"/>}</section>

    <section className="content-section"><div className="section-title-row"><div><span className="section-kicker">High signal</span><h2>Happening near you</h2></div><Link href="/discover?urgent=1">Last spots <ArrowUpRight size={16}/></Link></div>{snapshot.suggestions.length ? <div className="activity-grid">{snapshot.suggestions.slice(0,6).map(a=><ActivityCard key={a.id} activity={a}/>)}</div> : <EmptyState title="Your city is quiet right now" body="Be the person who changes that. Create a run, pickup game, class or anything active." href="/create?type=activity" action="Start something"/>}</section>

    <section className="home-two-col"><div className="content-section no-margin"><div className="section-title-row"><div><span className="section-kicker">Clan Pulse</span><h2>Your people</h2></div></div>{snapshot.clans.length ? <div className="stack-list">{snapshot.clans.slice(0,4).map(c=><ClanCard key={c.id} clan={c}/>)}</div> : <EmptyState title="No clan yet" body="Clans are Ojoro's home base for teams, activities and the people you keep moving with." href="/discover?tab=clans" action="Find a clan"/>}</div>
      <div className="content-section no-margin"><div className="section-title-row"><div><span className="section-kicker">Say what you're up for</span><h2>Ojoro Status</h2></div></div><form action={setStatusAction} className="status-composer"><div className="field"><label htmlFor="status-message">Available for...</label><input id="status-message" name="message" placeholder="Football tonight, gym at 6, anything outdoors..." maxLength={280} required/></div><div className="composer-row"><select name="sport" aria-label="Sport"><option value="">Any activity</option><option value="football">Football</option><option value="basketball">Basketball</option><option value="running">Running</option><option value="strength">Gym</option><option value="tennis">Tennis</option></select><button className="button button-brand" type="submit">Post status</button></div></form>{snapshot.statuses.length>0&&<div className="status-list">{snapshot.statuses.slice(0,4).map(s=><div className="status-item" key={s.id}><span>{sportEmoji(s.sport_slug??"")}</span><div><strong>{s.profile?.full_name??s.profile?.username??"Ojoro member"}</strong><p>{s.message}</p></div></div>)}</div>}</div></section>

    <section className="content-section"><div className="section-title-row"><div><span className="section-kicker">Progress that means something</span><h2>Your goals</h2></div><Link href="/you">Manage goals <ArrowUpRight size={16}/></Link></div>{snapshot.goals.length ? <div className="goal-grid">{snapshot.goals.map(g=><article className="goal-card" key={g.id}><div className="goal-head"><strong>{g.title}</strong><span>{Math.round(Number(g.current_value))} / {Math.round(Number(g.target_value))}</span></div><div className="progress-track"><span style={{width:`${percent(Number(g.current_value),Number(g.target_value))}%`}}/></div><small>{String(g.metric).replaceAll("_"," ")}</small></article>)}</div> : <EmptyState title="Pick something to work toward" body="A first 5K, four gym sessions a week, trying padel—your progress can be personal." href="/you" action="Set a goal"/>}</section>

    <section className="content-section"><div className="section-title-row"><div><span className="section-kicker">Activity drives the feed</span><h2>From your world</h2></div></div><form action={createPostAction} className="feed-composer"><textarea name="body" maxLength={3000} placeholder="Share an activity update, invite people out, celebrate a result..." required/><button className="button button-dark" type="submit">Post</button></form>{snapshot.feed.length ? <div className="feed-list">{snapshot.feed.map(item=><article className="feed-item" key={item.id}><div className="avatar avatar-sm">{(item.author?.full_name??item.author?.username??"O")[0].toUpperCase()}</div><div><div className="feed-author"><strong>{item.author?.full_name??item.author?.username??"Ojoro member"}</strong><span>{new Date(item.created_at).toLocaleDateString("en-CA",{month:"short",day:"numeric"})}</span></div><p>{item.body}</p></div></article>)}</div> : <p className="muted-copy">Your feed fills with real activity—clan updates, recaps, achievements and the people you move with.</p>}</section>
  </div>;
}
