import Link from "next/link";
import { notFound } from "next/navigation";
import { CalendarDays, CheckCircle2, MapPin, ShieldCheck, Trophy, Users } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { EmptyState } from "@/components/empty-state";
import { requireViewer } from "@/lib/auth";
import { unreadNotificationCount } from "@/lib/data";
import { formatActivityTime, sportEmoji, titleCase } from "@/lib/format";
import { rsvpActivityAction, reportEntityAction } from "@/lib/actions";
import { assignMatchSideAction, confirmMatchResultAction, createActivityRecapAction, recordAttendanceAction, submitMatchResultAction } from "@/lib/activity-actions";

export default async function ActivityPage({ params, searchParams }: { params: Promise<{id:string}>; searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const {id}=await params; const notice=await searchParams; const {supabase,user}=await requireViewer();
  const [{data:activity},{data:participants},{data:result},unread]=await Promise.all([
    supabase.from("oj_activities").select("id,organizer_id,clan_id,title,description,sport_slug,mode,skill_level,city,location_name,starts_at,ends_at,max_participants,cost_cents,urgent_spots,status,visibility").eq("id",id).maybeSingle(),
    supabase.from("oj_activity_participants").select("profile_id,rsvp_status,attendance,team_side,position,joined_at").eq("activity_id",id).order("joined_at"),
    supabase.from("oj_match_results").select("id,submitted_by,home_name,away_name,home_score,away_score,mvp_profile_id,status,verified_at").eq("activity_id",id).maybeSingle(),
    unreadNotificationCount(supabase,user.id)
  ]);
  if(!activity) notFound();
  const profileIds=[...new Set((participants??[]).map(p=>p.profile_id))]; let profiles:any[]=[]; if(profileIds.length){const {data}=await supabase.from("oj_profiles").select("id,username,full_name,avatar_url").in("id",profileIds); profiles=data??[];}
  const profileMap=new Map(profiles.map(p=>[p.id,p])); const going=(participants??[]).filter(p=>p.rsvp_status==="going"); const viewer=(participants??[]).find(p=>p.profile_id===user.id);
  let clanRole:string|null=null; if(activity.clan_id){const {data}=await supabase.from("oj_clan_members").select("role").eq("clan_id",activity.clan_id).eq("profile_id",user.id).eq("status","active").maybeSingle(); clanRole=data?.role??null;}
  const canManage=activity.organizer_id===user.id||["founder","leader","captain","coach","event_organizer"].includes(clanRole??"");
  const canConfirm=Boolean(result&&viewer?.rsvp_status==="going"&&result.status==="submitted");
  const {data:recaps}=await supabase.from("oj_posts").select("id,body,created_at").eq("activity_id",id).eq("kind","recap").order("created_at",{ascending:false}).limit(3);
  const error=typeof notice.error==="string"?notice.error:null; const ok=typeof notice.notice==="string"?notice.notice:null;
  return <div className="page-wrap"><AppHeader title={activity.title} eyebrow={`${sportEmoji(activity.sport_slug)} ${titleCase(activity.sport_slug)}`} unread={unread} actions={<Link href="/discover" className="button button-ghost desktop-action">Back to discover</Link>}/>
    {(error||ok)&&<div className={`flash ${error?"flash-error":"flash-ok"}`}>{error??ok}</div>}
    <section className="detail-hero"><div><div className="tag-row"><span className="tag">{titleCase(activity.mode)}</span>{activity.skill_level&&<span className="tag">{titleCase(activity.skill_level)}</span>}{activity.urgent_spots&&<span className="tag tag-hot">Needs players</span>}</div><h2>{activity.title}</h2><p>{activity.description||"No description yet. The important part is showing up."}</p><div className="detail-facts"><span><CalendarDays size={17}/>{formatActivityTime(activity.starts_at)}</span><span><MapPin size={17}/>{activity.location_name}, {activity.city}</span><span><Users size={17}/>{going.length}/{activity.max_participants} going</span>{activity.cost_cents>0&&<span>${(activity.cost_cents/100).toFixed(2)}</span>}</div></div><div className="detail-action-card"><strong>{viewer?.rsvp_status?`You’re ${titleCase(viewer.rsvp_status)}`:"Ready to move?"}</strong><form action={rsvpActivityAction}><input type="hidden" name="activity_id" value={id}/><div className="button-row"><button className="button button-primary" name="desired" value="going">I’m in</button><button className="button button-ghost" name="desired" value="maybe">Maybe</button>{viewer&&<button className="button button-ghost" name="desired" value="cancelled">Cancel</button>}</div></form></div></section>
    <section className="content-section"><div className="section-heading"><div><span className="section-kicker">People</span><h3>Who’s showing up</h3></div><span>{going.length} confirmed</span></div>{going.length?<div className="member-list">{going.map(p=>{const person=profileMap.get(p.profile_id);return <div className="member-row" key={p.profile_id}><div><strong>{person?.full_name||person?.username||"Ojoro member"}</strong><small>{p.team_side?`${titleCase(p.team_side)}${p.position?` · ${p.position}`:""}`:"Confirmed"}</small></div>{canManage&&<div className="inline-forms"><form action={recordAttendanceAction}><input type="hidden" name="activity_id" value={id}/><input type="hidden" name="profile_id" value={p.profile_id}/><select name="attendance" defaultValue={p.attendance||"attended"}><option value="attended">Attended</option><option value="excused">Excused</option><option value="late_cancel">Late cancel</option><option value="no_show">No-show</option></select><button className="button button-small">Save attendance</button></form>{activity.mode==="competitive"&&<form action={assignMatchSideAction}><input type="hidden" name="activity_id" value={id}/><input type="hidden" name="profile_id" value={p.profile_id}/><select name="side" defaultValue={p.team_side||"home"}><option value="home">Home</option><option value="away">Away</option></select><input name="position" defaultValue={p.position||""} placeholder="Position"/><button className="button button-small">Assign</button></form>}</div>}</div>})}</div>:<EmptyState title="Be the first one in" body="Someone has to make the first commitment. Others are more likely to follow." href="#rsvp" action="Join this activity"/>}</section>
    {activity.mode==="competitive"&&<section className="content-section"><div className="section-heading"><div><span className="section-kicker">Competition</span><h3>Verified result</h3></div><Trophy/></div>{result?<div className="scoreboard"><div><strong>{result.home_name}</strong><b>{result.home_score}</b></div><span>{titleCase(result.status)}</span><div><b>{result.away_score}</b><strong>{result.away_name}</strong></div></div>:<p className="muted">No result has been submitted yet.</p>}{canManage&&<form className="form-card compact-form" action={submitMatchResultAction}><input type="hidden" name="activity_id" value={id}/><div className="form-grid"><label>Home name<input name="home_name" defaultValue={result?.home_name||"Home"}/></label><label>Home score<input type="number" min="0" name="home_score" defaultValue={result?.home_score??0}/></label><label>Away name<input name="away_name" defaultValue={result?.away_name||"Away"}/></label><label>Away score<input type="number" min="0" name="away_score" defaultValue={result?.away_score??0}/></label></div><button className="button button-dark">Submit result</button></form>}{canConfirm&&<form action={confirmMatchResultAction} className="button-row"><input type="hidden" name="activity_id" value={id}/><input type="hidden" name="result_id" value={result!.id}/><button className="button button-primary" name="agrees" value="true"><CheckCircle2 size={17}/>Confirm result</button><button className="button button-ghost" name="agrees" value="false">Dispute</button></form>}</section>}
    <section className="content-section"><div className="section-heading"><div><span className="section-kicker">Afterglow</span><h3>Make the activity matter after it ends</h3></div><ShieldCheck/></div>{recaps?.length?<div className="feed-list">{recaps.map(r=><article className="feed-item" key={r.id}><p>{r.body}</p><small>{new Date(r.created_at).toLocaleString("en-CA")}</small></article>)}</div>:<p className="muted">No recap yet.</p>}{activity.organizer_id===user.id&&<form className="form-card compact-form" action={createActivityRecapAction}><input type="hidden" name="activity_id" value={id}/><textarea name="body" maxLength={3000} placeholder="What happened? Celebrate people, records, funny moments and what’s next."/><button className="button button-dark">Publish recap</button></form>}</section>
    <details className="safety-panel"><summary>Safety & reporting</summary><form action={reportEntityAction}><input type="hidden" name="entity_kind" value="activity"/><input type="hidden" name="entity_id" value={id}/><input type="hidden" name="back" value={`/activities/${id}`}/><label>Reason<select name="reason"><option>Unsafe behaviour</option><option>Misleading event information</option><option>Harassment</option><option>Spam</option></select></label><button className="button button-danger">Report activity</button></form></details>
  </div>;
}
