DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'aegis') THEN
    CREATE ROLE aegis LOGIN PASSWORD 'aegis-local-only' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  END IF;
END $$;

GRANT CONNECT ON DATABASE aegis TO aegis;
GRANT USAGE, CREATE ON SCHEMA public TO aegis;
