import { Award, CheckCircle2, Compass, Gauge, ShieldCheck, Target, Trophy } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { QueryNotice } from "@/components/empty-state";
import { saveGoalAction } from "@/lib/actions";
import { requireViewer } from "@/lib/auth";
import { profileSnapshot, unreadNotificationCount } from "@/lib/data";
import { ojoroScore } from "@/lib/domain/scoring";
import { percent, sportEmoji, titleCase } from "@/lib/format";
import { setCompetitionQuietAction, updateProfileAction } from "@/lib/profile-actions";

export default async function YouPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const {supabase,user,profile}=await requireViewer(); const ninety=new Date(Date.now()-90*86400000).toISOString();
  const [snapshot,unread,q,{data:participation},{count:organized},{data:challengeDone}]=await Promise.all([
    profileSnapshot(supabase,user.id),unreadNotificationCount(supabase,user.id),searchParams,
    supabase.from("oj_activity_participants").select("activity_id,attendance_status").eq("profile_id",user.id),
    supabase.from("oj_activities").select("id",{count:"exact",head:true}).eq("organizer_id",user.id).gte("starts_at",ninety),
    supabase.from("oj_challenge_members").select("challenge_id,completed_at").eq("profile_id",user.id).gte("completed_at",ninety)
  ]);
  const participantIds=(participation??[]).map(p=>p.activity_id); let recentActivities:any[]=[];
  if(participantIds.length){const {data}=await supabase.from("oj_activities").select("id,sport_slug,starts_at").in("id",participantIds).gte("starts_at",ninety);recentActivities=data??[];}
  const recentSet=new Set(recentActivities.map(a=>a.id)); const recentParticipation=(participation??[]).filter(p=>recentSet.has(p.activity_id));
  const attended=recentParticipation.filter(p=>p.attendance_status==="attended").length; const noShows=recentParticipation.filter(p=>p.attendance_status==="no_show").length;
  const weekKeys=new Set(recentActivities.map(a=>Math.floor(new Date(a.starts_at).getTime()/(7*86400000)))); const distinctSports=new Set(recentActivities.map(a=>a.sport_slug)).size;
  const score=ojoroScore({attended90d:attended,organized90d:organized??0,challengesCompleted90d:(challengeDone??[]).length,distinctSports90d:distinctSports,activeWeeks12:weekKeys.size,noShows90d:noShows,communityContributions90d:organized??0});
  const achievementSlugs=snapshot.achievements.map(a=>a.achievement_slug); let achievementDefs:any[]=[]; if(achievementSlugs.length){const {data}=await supabase.from("oj_achievement_definitions").select("slug,name,description,icon").in("slug",achievementSlugs);achievementDefs=data??[];} const defMap=new Map(achievementDefs.map(a=>[a.slug,a]));
  const clanIds=snapshot.memberships.map(m=>m.clan_id); let clans:any[]=[]; if(clanIds.length){const {data}=await supabase.from("oj_clans").select("id,name,slug").in("id",clanIds);clans=data??[];} const clanMap=new Map(clans.map(c=>[c.id,c]));
  const error=typeof q.error==="string"?q.error:null; const success=q.saved?"Profile saved.":q.goal?"Goal created.":q.competition?"Competition preference updated.":null;
  return <div className="page-wrap"><AppHeader title="You" eyebrow="Your sports résumé" unread={unread}/><QueryNotice error={error} success={success}/>
    <section className="profile-hero"><div className="profile-avatar">{(profile.full_name??String(profile.username))[0].toUpperCase()}</div><div className="profile-main"><div className="profile-name-line"><h2>{profile.full_name??profile.username}</h2>{profile.verified_organizer&&<ShieldCheck aria-label="Verified organizer"/>}</div><p>@{String(profile.username)} · {profile.city||"City not set"}</p><div className="pill-row">{snapshot.sports.slice(0,5).map(s=><span className="soft-pill" key={s.sport_slug}>{sportEmoji(s.sport_slug)} {titleCase(s.sport_slug)}</span>)}</div></div><div className="level-block"><span>LEVEL</span><strong>{profile.level}</strong><small>{profile.lifetime_xp.toLocaleString()} XP</small></div></section>

    <div className="profile-stat-grid"><article><Gauge/><span>Ojoro Score</span><strong>{score}</strong><small>out of 1,000</small></article><article><CheckCircle2/><span>Reliability</span><strong>{snapshot.reputation?.reliability_percent==null?"—":`${snapshot.reputation.reliability_percent}%`}</strong><small>{snapshot.reputation?.considered_events??0} recent events</small></article><article><Compass/><span>Passport</span><strong>{snapshot.passport.length}</strong><small>sports tried</small></article><article><Trophy/><span>Clans</span><strong>{snapshot.memberships.length}</strong><small>communities</small></article></div>

    <section className="content-section"><div className="section-title-row"><div><span className="section-kicker">Ojoro Passport</span><h2>Your movement story</h2></div></div>{snapshot.passport.length?<div className="passport-grid">{snapshot.passport.map(p=><article key={p.sport_slug}><span>{sportEmoji(p.sport_slug)}</span><div><strong>{titleCase(p.sport_slug)}</strong><small>{p.activities} activities · since {new Date(p.first_played_at).toLocaleDateString("en-CA",{month:"short",year:"numeric"})}</small></div></article>)}</div>:<div className="inline-empty">Show up to your first Ojoro activity and your Passport starts here.</div>}</section>

    <section className="profile-two-col"><div className="content-section no-margin"><div className="section-title-row"><div><span className="section-kicker">Goals</span><h2>What you're building toward</h2></div></div>{snapshot.goals.length?<div className="stack-list">{snapshot.goals.map(g=><article className="goal-card" key={g.id}><div className="goal-head"><strong>{g.title}</strong><span>{Number(g.current_value)} / {Number(g.target_value)}</span></div><div className="progress-track"><span style={{width:`${percent(Number(g.current_value),Number(g.target_value))}%`}}/></div><small>{titleCase(g.metric)}</small></article>)}</div>:null}<form action={saveGoalAction} className="mini-form"><h3><Target size={18}/> Add a goal</h3><input name="title" placeholder="Run my first 5K" required/><div className="form-grid-2"><input name="metric" placeholder="kilometres" required/><input name="target" type="number" min="0.1" step="0.1" placeholder="5" required/></div><button className="button button-dark" type="submit">Save goal</button></form></div>
      <div className="content-section no-margin"><div className="section-title-row"><div><span className="section-kicker">Community identity</span><h2>Your roles</h2></div></div>{snapshot.memberships.length?<div className="role-list">{snapshot.memberships.map(m=><div key={m.clan_id}><div className="clan-badge mini">{(clanMap.get(m.clan_id)?.name??"OJ").slice(0,2).toUpperCase()}</div><div><strong>{clanMap.get(m.clan_id)?.name??"Clan"}</strong><small>{titleCase(m.role)}</small></div></div>)}</div>:<div className="inline-empty">Join a clan to build your community history.</div>}</div></section>

    <section className="content-section"><div className="section-title-row"><div><span className="section-kicker">Achievements</span><h2>Earned, not bought</h2></div></div>{snapshot.achievements.length?<div className="achievement-grid">{snapshot.achievements.map(a=>{const d=defMap.get(a.achievement_slug);return <article key={a.achievement_slug}><span>{d?.icon??"🏅"}</span><strong>{d?.name??titleCase(a.achievement_slug)}</strong><p>{d?.description??"Ojoro achievement"}</p></article>})}</div>:<div className="inline-empty"><Award/> Your first achievement unlocks when you start participating.</div>}</section>

    <section className="settings-grid"><div className="content-section no-margin" id="competition"><div className="section-title-row"><div><span className="section-kicker">Competition</span><h2>Choose your relationship with rankings</h2></div></div><p className="muted-copy">Quiet Mode removes leaderboard pressure while preserving your private ratings and every non-competitive part of Ojoro.</p><form action={setCompetitionQuietAction}><input type="hidden" name="enabled" value={profile.competition_quiet?"false":"true"}/><button className="button button-ghost" type="submit">{profile.competition_quiet?"Show my ranking surfaces":"Turn on Competition Quiet Mode"}</button></form></div>
      <div className="content-section no-margin"><div className="section-title-row"><div><span className="section-kicker">Profile</span><h2>Basics</h2></div></div><form action={updateProfileAction} className="form-stack"><div className="field"><label htmlFor="p_name">Name</label><input id="p_name" name="full_name" defaultValue={profile.full_name??""} required/></div><div className="field"><label htmlFor="p_city">City</label><input id="p_city" name="city" defaultValue={profile.city??""} required/></div><div className="field"><label htmlFor="p_bio">Bio</label><textarea id="p_bio" name="bio" defaultValue={profile.bio??""} maxLength={600}/></div><button className="button button-dark" type="submit">Save profile</button></form></div></section>
  </div>;
}
