import Link from "next/link";
import { notFound } from "next/navigation";
import { ShieldCheck, Trophy, Users } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { ActivityCard } from "@/components/activity-card";
import { requireViewer } from "@/lib/auth";
import { hydrateActivities, unreadNotificationCount } from "@/lib/data";
import { titleCase } from "@/lib/format";
import { joinClanAction, reportEntityAction } from "@/lib/actions";
import { addTeamMemberAction, createTeamAction, leaveClanAction, reviewClanRequestAction, setClanRoleAction } from "@/lib/clan-actions";

export default async function ClanPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {slug}=await params; const query=await searchParams; const {supabase,user}=await requireViewer();
 const [{data:clan},unread]=await Promise.all([supabase.from("oj_clans").select("id,owner_id,slug,name,bio,city,is_public,level,lifetime_xp,verified_state,created_at").eq("slug",slug).maybeSingle(),unreadNotificationCount(supabase,user.id)]); if(!clan) notFound();
 const [{data:sports},{data:members},{data:teams},{data:activityRows}]=await Promise.all([
   supabase.from("oj_clan_sports").select("sport_slug,is_primary").eq("clan_id",clan.id),
   supabase.from("oj_clan_members").select("profile_id,role,status,joined_at").eq("clan_id",clan.id).order("joined_at"),
   supabase.from("oj_teams").select("id,sport_slug,name,description,created_at").eq("clan_id",clan.id).order("created_at"),
   supabase.from("oj_activities").select("id,title,sport_slug,mode,skill_level,city,location_name,starts_at,max_participants,cost_cents,urgent_spots").eq("clan_id",clan.id).gte("starts_at",new Date().toISOString()).eq("status","scheduled").order("starts_at").limit(8)
 ]);
 const ids=[...new Set((members??[]).map(m=>m.profile_id))]; let profiles:any[]=[]; if(ids.length){const {data}=await supabase.from("oj_profiles").select("id,username,full_name,avatar_url").in("id",ids); profiles=data??[];} const profileMap=new Map(profiles.map(p=>[p.id,p]));
 const viewerMember=(members??[]).find(m=>m.profile_id===user.id); const role=viewerMember?.status==="active"?viewerMember.role:null; const canManage=["founder","leader"].includes(role??""); const canTeams=["founder","leader","captain","coach"].includes(role??""); const active=(members??[]).filter(m=>m.status==="active"); const pending=(members??[]).filter(m=>m.status==="pending");
 const activities=await hydrateActivities(supabase,activityRows,user.id); const error=typeof query.error==="string"?query.error:null; const notice=typeof query.notice==="string"?query.notice:null;
 return <div className="page-wrap"><AppHeader title={clan.name} eyebrow={`${clan.city} · Clan`} unread={unread} actions={<Link className="button button-dark desktop-action" href={`/create?type=activity&clan=${clan.id}`}>Create activity</Link>}/>{(error||notice)&&<div className={`flash ${error?"flash-error":"flash-ok"}`}>{error??notice}</div>}
   <section className="detail-hero clan-hero"><div><div className="tag-row">{clan.verified_state!=="unverified"&&<span className="tag"><ShieldCheck size={14}/>Verified</span>}{sports?.map(s=><span className="tag" key={s.sport_slug}>{titleCase(s.sport_slug)}</span>)}</div><h2>{clan.name}</h2><p>{clan.bio||"A community built around showing up and doing things together."}</p><div className="detail-facts"><span><Users size={17}/>{active.length} members</span><span><Trophy size={17}/>Level {clan.level}</span><span>{clan.lifetime_xp.toLocaleString()} clan XP</span></div></div><div className="detail-action-card">{viewerMember?.status==="active"?<><strong>{titleCase(viewerMember.role)}</strong>{viewerMember.role!=="founder"&&<form action={leaveClanAction}><input type="hidden" name="clan_id" value={clan.id}/><input type="hidden" name="slug" value={slug}/><button className="button button-ghost">Leave clan</button></form>}</>:<form action={joinClanAction}><input type="hidden" name="clan_id" value={clan.id}/><input type="hidden" name="slug" value={slug}/><button className="button button-primary">{clan.is_public?"Join clan":"Request to join"}</button></form>}</div></section>
   {pending.length>0&&canManage&&<section className="content-section"><div className="section-heading"><div><span className="section-kicker">Requests</span><h3>People waiting to join</h3></div><span>{pending.length}</span></div><div className="member-list">{pending.map(m=>{const p=profileMap.get(m.profile_id);return <div className="member-row" key={m.profile_id}><strong>{p?.full_name||p?.username||"Member"}</strong><form className="button-row" action={reviewClanRequestAction}><input type="hidden" name="clan_id" value={clan.id}/><input type="hidden" name="slug" value={slug}/><input type="hidden" name="profile_id" value={m.profile_id}/><button className="button button-small" name="decision" value="approve">Approve</button><button className="button button-small button-ghost" name="decision" value="decline">Decline</button></form></div>})}</div></section>}
   <section className="content-section"><div className="section-heading"><div><span className="section-kicker">Structure</span><h3>Members & roles</h3></div><span>{active.length} active</span></div><div className="member-list">{active.map(m=>{const p=profileMap.get(m.profile_id);return <div className="member-row" key={m.profile_id}><div><strong>{p?.full_name||p?.username||"Member"}</strong><small>{titleCase(m.role)}</small></div>{canManage&&m.profile_id!==clan.owner_id&&<form action={setClanRoleAction} className="inline-form"><input type="hidden" name="clan_id" value={clan.id}/><input type="hidden" name="slug" value={slug}/><input type="hidden" name="profile_id" value={m.profile_id}/><select name="role" defaultValue={m.role}><option value="leader">Leader</option><option value="captain">Captain</option><option value="coach">Coach</option><option value="event_organizer">Event organizer</option><option value="moderator">Moderator</option><option value="member">Member</option></select><button className="button button-small">Update</button></form>}</div>})}</div></section>
   <section className="content-section"><div className="section-heading"><div><span className="section-kicker">Teams</span><h3>Sport groups inside the clan</h3></div><span>{teams?.length??0}</span></div>{teams?.length?<div className="team-grid">{teams.map(t=><article className="team-card" key={t.id}><span>{titleCase(t.sport_slug)}</span><h4>{t.name}</h4><p>{t.description||"Clan team"}</p>{canTeams&&active.length>1&&<form action={addTeamMemberAction}><input type="hidden" name="team_id" value={t.id}/><input type="hidden" name="slug" value={slug}/><select name="profile_id">{active.filter(m=>m.profile_id!==user.id).map(m=><option key={m.profile_id} value={m.profile_id}>{profileMap.get(m.profile_id)?.full_name||profileMap.get(m.profile_id)?.username||"Member"}</option>)}</select><button className="button button-small">Add member</button></form>}</article>)}</div>:<p className="muted">No teams yet. Multi-sport clans can organize separate teams without splitting the community.</p>}{canTeams&&<form className="form-card compact-form" action={createTeamAction}><input type="hidden" name="clan_id" value={clan.id}/><input type="hidden" name="slug" value={slug}/><div className="form-grid"><label>Team name<input name="name" required minLength={2} maxLength={80}/></label><label>Sport<select name="sport">{sports?.map(s=><option key={s.sport_slug} value={s.sport_slug}>{titleCase(s.sport_slug)}</option>)}</select></label></div><label>Description<textarea name="description" maxLength={500}/></label><button className="button button-dark">Create team</button></form>}</section>
   <section className="content-section"><div className="section-heading"><div><span className="section-kicker">Next up</span><h3>Clan activities</h3></div></div>{activities.length?<div className="activity-grid">{activities.map(a=><ActivityCard key={a.id} activity={a}/>)}</div>:<p className="muted">No upcoming activities yet.</p>}</section>
   <details className="safety-panel"><summary>Report this clan</summary><form action={reportEntityAction}><input type="hidden" name="entity_kind" value="clan"/><input type="hidden" name="entity_id" value={clan.id}/><input type="hidden" name="back" value={`/clans/${slug}`}/><select name="reason"><option>Unsafe behaviour</option><option>Harassment</option><option>Misleading information</option><option>Spam</option></select><button className="button button-danger">Submit report</button></form></details>
 </div>;
}
