import Link from "next/link";
import { ArrowUpRight, Flag, LockKeyhole, Medal, Trophy } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { EmptyState, QueryNotice } from "@/components/empty-state";
import { joinChallengeAction } from "@/lib/actions";
import { requireViewer } from "@/lib/auth";
import { competeSnapshot, unreadNotificationCount } from "@/lib/data";
import { titleCase } from "@/lib/format";

export default async function CompetePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const {supabase,user,profile}=await requireViewer(); const [data,unread,q]=await Promise.all([competeSnapshot(supabase,user.id),unreadNotificationCount(supabase,user.id),searchParams]);
  const success=q.joined?"Challenge joined.":q.created?"Challenge launched.":q.tournament?"Tournament registration is open.":null;
  return <div className="page-wrap"><AppHeader title="Compete" eyebrow="Compare when it motivates you" unread={unread} actions={<Link href="/create?type=challenge" className="button button-dark desktop-action">Create challenge</Link>}/><QueryNotice success={success}/>
    <section className="compete-hero"><div><span className="daily-label"><Trophy size={15}/> Fall 2026</span><h2>Competition without making <em>everything</em> competitive.</h2><p>Ratings are sport-specific and seasonal. Social, fitness and learning activities never quietly change your serious ranking.</p></div><div className="competition-state">{profile.competition_quiet?<><LockKeyhole/><strong>Quiet mode on</strong><span>Leaderboards hidden</span></>:<><Medal/><strong>Rankings visible</strong><span>Your competitive mode</span></>}</div></section>

    <section className="content-section"><div className="section-title-row"><div><span className="section-kicker">Active challenges</span><h2>Give yourself a target</h2></div><Link href="/create?type=challenge">Make one <ArrowUpRight size={16}/></Link></div>{data.challenges.length?<div className="challenge-grid">{data.challenges.map(c=>{const joined=Boolean(c.membership);const progress=Number(c.membership?.progress??0);const target=Number(c.target_value);return <article className="challenge-card" key={c.id}><div className="challenge-icon"><Flag/></div><div className="challenge-copy"><div className="pill-row"><span className="soft-pill">{titleCase(c.scope)}</span><span className="soft-pill">+{c.xp_reward} XP</span></div><h3>{c.title}</h3><p>{c.description||`${target} ${c.metric}`}</p>{joined?<><div className="progress-track"><span style={{width:`${Math.min(100,Math.round(progress/target*100))}%`}}/></div><small>{progress} / {target} {c.metric}</small></>:<form action={joinChallengeAction}><input type="hidden" name="challenge_id" value={c.id}/><button className="button button-ghost" type="submit">Join challenge</button></form>}</div></article>})}</div>:<EmptyState title="No active challenges yet" body="Create a useful reason for yourself, friends, a clan or your city to move." href="/create?type=challenge" action="Create a challenge"/>}</section>

    <section className="content-section"><div className="section-title-row"><div><span className="section-kicker">Sport rating</span><h2>{data.primarySport?`${titleCase(data.primarySport)} leaderboard`:"Your leaderboard"}</h2></div></div>{profile.competition_quiet?<div className="quiet-panel"><LockKeyhole/><div><h3>Competition Quiet Mode is on</h3><p>Your ratings are preserved, but ranking surfaces stay hidden. Personal progress, clans, challenges and achievements still work normally.</p><Link href="/you#competition">Change preference</Link></div></div>:data.primarySport&&data.leaderboard.length?<div className="leaderboard"><div className="leaderboard-head"><span>Rank</span><span>Athlete</span><span>Rating</span><span>Record</span></div>{data.leaderboard.map((row,index)=><div className={`leaderboard-row ${row.profile_id===user.id?"is-you":""}`} key={row.profile_id}><strong>#{index+1}</strong><div className="leaderboard-person"><div className="avatar avatar-sm">{(row.full_name??row.username)[0].toUpperCase()}</div><span>{row.full_name??row.username}{row.profile_id===user.id&&<small>You</small>}</span></div><strong>{row.rating}</strong><span>{row.wins}-{row.losses}{row.draws?`-${row.draws}`:""}</span></div>)}</div>:<EmptyState title="No rated games yet" body="Competitive ratings begin only after a result is verified. Casual activity never counts by accident." href="/create?type=match" action="Create a match"/>}</section>
  </div>;
}
